version: "3.4"

services:
  postgres:
    container_name: ncs-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ncs
      POSTGRES_PASSWORD: "1234"


volumes:
  postgres_data: